WebSite/src/main/java/com/jjmsoftsolutions/bean/PollBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.entity.Poll;
import com.jjmsoftsolutions.entity.PollOptions;
import com.jjmsoftsolutions.entity.PollStats;
import com.jjmsoftsolutions.model.PollModel;
import com.jjmsoftsolutions.utils.Session;
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "PollBean")
@ViewScoped
public class PollBean implements Serializable{


    private Poll poll;

    public Poll getUltimatePoll() {
        setPoll(PollModel.getLastPoll());
        return getPoll();
    }

    /**
     * @return the poll
     */
    public Poll getPoll() {
        return poll;
    }

    /**
     * @param poll the poll to set
     */
    public void setPoll(Poll poll) {
        this.poll = poll;
    }

    
    public void vote(Integer selectedOption) {
        PollStats stats = new PollStats();
        stats.setEmail(Session.getUser());
        stats.setIdPollOption(new PollOptions(selectedOption));
        stats.setIdPoll(poll);
        PollModel.setVote(stats);       
    }
    
    public void delete(Integer selectedOption) {   
        PollModel.delete(selectedOption);       
    }
    
     public void change(Integer delete, Integer insert) {
         delete(delete);
         vote(insert);
    }

}

WebSite/src/main/java/com/jjmsoftsolutions/bean/PostBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.domain.Tag;
import com.jjmsoftsolutions.entity.Post;
import com.jjmsoftsolutions.entity.PostComment;
import com.jjmsoftsolutions.model.PostModel;
import com.jjmsoftsolutions.model.VideoModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "PostBean")
@ViewScoped
public class PostBean implements Serializable {

    private Post post;
    private List<Post> popular;
    private List<Post> news;

    private PostComment comment = new PostComment();

    public Post getLastPost() {
        setPost(PostModel.getLastPost("Reflexion"));
        return getPost();
    }

    public List<Post> getEvents() {
        String category = "Eventos";
        int end = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        return PostModel.getAllPostByCategory(category, end);
    }

    public Post getPostById() {
        setPost(PostModel.getPostById(StringUtils.getInt(JSFUtil.getParameterURL("id"))));
        return getPost();
    }

    public Post getEventById() {
        setPost(PostModel.getPostByIdCategory(StringUtils.getInt(JSFUtil.getParameterURL("id")), "Eventos"));
        return getPost();
    }

    public List<Post> getPopularPost() {
        setPopular(PostModel.getPopularPost(8));
        return getPopular();
    }

    public List<Post> getCuriosities() {
        return PostModel.getPostByCategory("Curiosidades", 10);
    }

    public List<Post> getNewsIndex() {
        setNews(PostModel.getPostByCategory("Eventos", 9));
        return getNews();
    }

    /**
     * @return the post
     */
    public Post getPost() {
        return post;
    }

    /**
     * @param post the post to set
     */
    public void setPost(Post post) {
        this.post = post;
    }

    /**
     * @return the popular
     */
    public List<Post> getPopular() {
        return popular;
    }

    /**
     * @param popular the popular to set
     */
    public void setPopular(List<Post> popular) {
        this.popular = popular;
    }

    /**
     * @return the news
     */
    public List<Post> getNews() {
        return news;
    }

    /**
     * @param news the news to set
     */
    public void setNews(List<Post> news) {
        this.news = news;
    }

    public void postComment() {
        getComment().setCommentDate(new Date());
        getComment().setEmail(Session.getUser());
        getComment().setIdPost(post);
        PostModel.postComment(getComment());
        Utility.redirect("Post?id=" + post.getIdPost());
    }

    /**
     * @return the comment
     */
    public PostComment getComment() {
        return comment;
    }

    /**
     * @param comment the comment to set
     */
    public void setComment(PostComment comment) {
        this.comment = comment;
    }

    public void deletePostComment(int id) {
        PostModel.delete(id);
        Utility.redirect("post.xhtml?id=" + post.getIdPost());
    }

    public List<Tag> getTotalButtons() {

        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        int totalRecord = PostModel.getCountByCategory("Eventos");
        return Utility.getTag(3, totalRecord, pagination);
    }

    public List<PostComment> getCommentsByBlog() {
        String email = JSFUtil.getParameterURL("id");
        int totalRecords = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        return PostModel.getAllPostByCommentsByBlog(email, totalRecords);
    }

    public List<Tag> getTotalCommentsPost() {
        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        int totalRecord = PostModel.getCountCommentsByBlog(JSFUtil.getParameterURL("id"));
        return Utility.getTag(3, totalRecord, pagination);

    }

}

WebSite/src/main/java/com/jjmsoftsolutions/entity/Poll.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jjmsoftsolutions.entity;

import com.jjmsoftsolutions.domain.Statistic;
import com.jjmsoftsolutions.model.PollModel;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author luis
 */
@Entity
@Table(name = "POLL")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Poll.findAll", query = "SELECT p FROM Poll p"),
    @NamedQuery(name = "Poll.findByIdPoll", query = "SELECT p FROM Poll p WHERE p.idPoll = :idPoll"),
    @NamedQuery(name = "Poll.findByQuestion", query = "SELECT p FROM Poll p WHERE p.question = :question"),
    @NamedQuery(name = "Poll.findByPollDate", query = "SELECT p FROM Poll p WHERE p.pollDate = :pollDate")})
public class Poll implements Serializable {
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idPoll", fetch = FetchType.LAZY)
    private List<PollStats> pollStatsList;
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID_POLL")
    private Integer idPoll;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 150)
    @Column(name = "QUESTION")
    private String question;
    @Basic(optional = false)
    @NotNull
    @Column(name = "POLL_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date pollDate;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idPoll", fetch = FetchType.LAZY)
    private List<PollOptions> pollOptionsList;

    public Poll() {
    }

    public Poll(Integer idPoll) {
        this.idPoll = idPoll;
    }

    public Poll(Integer idPoll, String question, Date pollDate) {
        this.idPoll = idPoll;
        this.question = question;
        this.pollDate = pollDate;
    }

    public Integer getIdPoll() {
        return idPoll;
    }

    public void setIdPoll(Integer idPoll) {
        this.idPoll = idPoll;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public Date getPollDate() {
        return pollDate;
    }

    public void setPollDate(Date pollDate) {
        this.pollDate = pollDate;
    }

    @XmlTransient
    public List<PollOptions> getPollOptionsList() {
        return pollOptionsList;
    }

    public void setPollOptionsList(List<PollOptions> pollOptionsList) {
        this.pollOptionsList = pollOptionsList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idPoll != null ? idPoll.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Poll)) {
            return false;
        }
        Poll other = (Poll) object;
        if ((this.idPoll == null && other.idPoll != null) || (this.idPoll != null && !this.idPoll.equals(other.idPoll))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.jjmsoftsolutions.entity.Poll[ idPoll=" + idPoll + " ]";
    }
    
    public List<Statistic> getPercentage(){
        return PollModel.getStatisTic(idPoll);
    }
    
    public PollStats getUserVote(){
        return PollModel.userVote(idPoll);
    }

    @XmlTransient
    public List<PollStats> getPollStatsList() {
        return pollStatsList;
    }

    public void setPollStatsList(List<PollStats> pollStatsList) {
        this.pollStatsList = pollStatsList;
    }
    
}

WebSite/src/main/java/com/jjmsoftsolutions/entity/Video.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jjmsoftsolutions.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author luis
 */
@Entity
@Table(name = "VIDEO")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Video.findAll", query = "SELECT v FROM Video v"),
    @NamedQuery(name = "Video.findByIdVideo", query = "SELECT v FROM Video v WHERE v.idVideo = :idVideo"),
    @NamedQuery(name = "Video.findByVideoDate", query = "SELECT v FROM Video v WHERE v.videoDate = :videoDate")})
public class Video implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID_VIDEO")
    private Integer idVideo;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 2147483647)
    @Column(name = "URL")
    private String url;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 2147483647)
    @Column(name = "TITLE")
    private String title;
    @Lob
    @Size(max = 2147483647)
    @Column(name = "DESCRIPTION")
    private String description;
    @Basic(optional = false)
    @NotNull
    @Column(name = "VIDEO_DATE")
    @Temporal(TemporalType.DATE)
    private Date videoDate;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idVideo", fetch = FetchType.LAZY)
    private List<VideoComments> videoCommentsList;
    @JoinColumn(name = "ID_EXPONENT", referencedColumnName = "ID_EXPONENT")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Exponent idExponent;
    @JoinColumn(name = "ID_VIDEO_ALBUM", referencedColumnName = "ID_VIDEO_ALBUM")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private VideoAlbum idVideoAlbum;

    public Video() {
    }

    public Video(Integer idVideo) {
        this.idVideo = idVideo;
    }

    public Video(Integer idVideo, String url, String title, Date videoDate) {
        this.idVideo = idVideo;
        this.url = url;
        this.title = title;
        this.videoDate = videoDate;
    }

    public Integer getIdVideo() {
        return idVideo;
    }

    public void setIdVideo(Integer idVideo) {
        this.idVideo = idVideo;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getVideoDate() {
        return videoDate;
    }

    public void setVideoDate(Date videoDate) {
        this.videoDate = videoDate;
    }

    @XmlTransient
    public List<VideoComments> getVideoCommentsList() {
        return videoCommentsList;
    }

    public void setVideoCommentsList(List<VideoComments> videoCommentsList) {
        this.videoCommentsList = videoCommentsList;
    }

    public Exponent getIdExponent() {
        return idExponent;
    }

    public void setIdExponent(Exponent idExponent) {
        this.idExponent = idExponent;
    }

    public VideoAlbum getIdVideoAlbum() {
        return idVideoAlbum;
    }

    public void setIdVideoAlbum(VideoAlbum idVideoAlbum) {
        this.idVideoAlbum = idVideoAlbum;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idVideo != null ? idVideo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Video)) {
            return false;
        }
        Video other = (Video) object;
        if ((this.idVideo == null && other.idVideo != null) || (this.idVideo != null && !this.idVideo.equals(other.idVideo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.jjmsoftsolutions.entity.Video[ idVideo=" + idVideo + " ]";
    }

    public String getImage() {
        return "http://img.youtube.com/vi/" + getCode() + "/0.jpg";
    }

    public String getURLYoutube() {
        return "http://www.youtube.com/embed/" + getCode() + "?wmode=transparent";
    }

    public String getCode() {
        String img;
        if (this.url.contains("https")) {
            img = this.url.substring(32);
        } else {
            img = this.url.substring(31);
        }
        return img;
    }

}

WebSite/src/main/webapp/View/Index/Curiosities.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <div class="widget">
        <div class="latest_tweets">
            <h4> <i ></i>  Curiosidades <small> Biblicas </small> </h4>
            <div class="tweets">
                <div class="tweets_slider owl-carousel owl-theme">
                    <ui:repeat value="#{PostBean.curiosities}" var="post" varStatus="status">
                        <div class="item clearfix">
                            #{post.description}
                            <a href="#{post.picture}">Leer versículo</a> 
                            <br/><br/>	
                            #{post.postDate} 
                        </div><!-- /slide -->
                    </ui:repeat>
                </div><!-- /tweets slider -->
            </div><!-- /tweets -->
        </div><!-- /latest tweets -->
    </div><!-- /widget -->
</ui:composition>

WebSite/src/main/webapp/View/Index/Events.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <div class="posts_block mbf clearfix">
        <div class="title color3">
            <h4>Eventos</h4>
        </div>
        <ui:repeat value="#{PostBean.newsIndex}" var="post" varStatus="status">
            <ui:fragment rendered="#{((status.index)) eq 0}">
                <div class="grid_6 alpha">
                    <div class="mb hover-shadow">
                        <a href="Evento?id=#{post.idPost}">
                            <img src="#{post.picture}" />
                        </a>
                    </div>
                    <div class="post_m_content">
                        <h3>
                            <a href="Evento?id=#{post.idPost}">#{post.title}</a>
                        </h3>
                        <div class="meta mb"> 
                            <p> #{post.description} </p>
                        </div>
                    </div>
                </div>
            </ui:fragment>
        </ui:repeat>

        <ui:fragment rendered="#{PostBean.news.size() gt 1}">
            <div class="grid_6 omega">
                <div class="small_slider_travel owl-carousel owl-theme">
                    <div class="item clearfix">
                        <ul class="small_posts">
                            <ui:repeat value="#{PostBean.news}" var="post" varStatus="status">
                                <ui:fragment rendered="#{(status.index) gt 0 and (status.index) lt 5}">
                                    <li class="clearfix">
                                        <a class="s_thumb hover-shadow" href="Evento?id=#{post.idPost}">
                                            <img width="70" height="70" src="#{post.picture}"/>
                                        </a>
                                        <h3>
                                            <a href="Evento?id=#{post.idPost}">#{post.title}</a>
                                        </h3>
                                        <div class="meta mb"> 
                                            <p> #{post.description} </p>
                                        </div>
                                    </li>
                                </ui:fragment>
                            </ui:repeat>
                        </ul>
                    </div>

                    <div class="item clearfix">
                        <ul class="small_posts">
                            <ui:repeat value="#{VideoBean.music}" var="video" varStatus="status">
                                <ui:fragment rendered="#{(status.index) gt 3 and (status.index) lt 8}">
                                    <li class="clearfix">
                                        <a class="s_thumb hover-shadow" href="Evento?id=#{post.idPost}">
                                            <img width="70" height="70" src="#{post.picture}"/>
                                        </a>
                                        <h3>
                                            <a href="Evento?id=#{post.idPost}">#{post.title}</a>
                                        </h3>
                                        <div class="meta mb"> 
                                            <p> #{post.description} </p>
                                        </div>
                                    </li>
                                </ui:fragment>
                            </ui:repeat>
                        </ul>
                    </div>
                </div>
            </div>
        </ui:fragment>

    </div>
</ui:composition>

WebSite/src/main/webapp/View/Index/Music.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">


    <div class="posts_block mbf clearfix">
        <div class="title color1">
            <h4>¿Quién dijo que la música cristiana es aburrida?</h4>
        </div>
        <ui:repeat value="#{VideoBean.musicIndex}" var="video" varStatus="status">
            <ui:fragment rendered="#{((status.index)) eq 0}">
                <div class="grid_6 alpha">
                    <div class="mb hover-shadow">
                        <div class="youtube_big">
                            <video id="example_video_1" class="video-js vjs-default-skin" controls="none" width="420" height="349"
                                   data-setup='{"techOrder":["youtube","html5"],"ytcontrols":false}'>
                                <source src="#{video.url}" type='video/youtube' />
                            </video>
                        </div>
                    </div>
                    <div class="post_m_content">
                        <h3>
                            <a href="#{video.url}">#{video.title}</a>
                        </h3>
                        <div class="meta mb"> 
                            <p> #{video.description} </p>
                        </div>
                    </div>
                </div>
            </ui:fragment>
        </ui:repeat>


        <div class="grid_6 omega">
            <div class="small_slider_travel owl-carousel owl-theme">
                <div class="item clearfix">
                    <ul class="small_posts">
                        <ui:repeat value="#{VideoBean.music}" var="video" varStatus="status">
                            <ui:fragment rendered="#{(status.index) gt 0 and (status.index) lt 5}">
                                <li class="clearfix">
                                    <a class="s_thumb hover-shadow" href="#{video.url}" target="_blank">
                                        <img width="150" height="100" src="#{video.image}"/>
                                    </a>
                                    <h4>
                                        <a href="#{video.url}" target="_blank">#{video.title}</a>
                                    </h4>
                                    <div class="meta mb"> 
                                        <p> #{video.description} </p>
                                    </div>
                                </li>
                            </ui:fragment>
                        </ui:repeat>
                    </ul>
                </div>

                <div class="item clearfix">
                    <ul class="small_posts">
                        <ui:repeat value="#{VideoBean.music}" var="video" varStatus="status">
                            <ui:fragment rendered="#{(status.index) gt 3 and (status.index) lt 8}">
                                <li class="clearfix">
                                    <a class="s_thumb hover-shadow" href="#{video.url}" target="_blank">
                                        <img width="150" height="100" src="#{video.image}"/>
                                    </a>
                                    <h3>
                                        <a href="#{video.url}" target="_blank">#{video.title}</a>
                                    </h3>
                                    <div class="meta mb"> 
                                        <p> #{video.description} </p>
                                    </div>
                                </li>
                            </ui:fragment>
                        </ui:repeat>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</ui:composition>

WebSite/src/main/webapp/View/Index/Poll.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:form>


        <div class="widget">
            <div class="title">
                <h4>Vos tambien contas</h4></div>
            <div class="wp-polls">

                <p class="tac">
                    <strong>#{PollBean.ultimatePoll.question}</strong>
                </p>
                <div class="wp-polls-ans">
                    <ul class="wp-polls-ul">
                        <ui:repeat value="#{PollBean.poll.pollOptionsList}" var="poll" varStatus="status" >

                            <ui:fragment rendered="#{(login.isLogin)}">
                                <li style="height: 27px">                                    
                                    <ui:fragment rendered="#{(poll.idPoll.userVote.idPollOption.idPollOptions) eq (poll.idPollOptions)}">
                                        <h:commandButton styleClass="vote-success" type="submit" actionListener="#{PollBean.delete(poll.pollStat.idPollStats)}" value="Eliminar"/>   
                                    </ui:fragment>

                                    <ui:fragment rendered="#{((poll.idPoll.userVote.idPollOption.idPollOptions) ne (poll.idPollOptions)) and  (poll.idPoll.userVote.idPollOption eq null)}">
                                        <h:commandButton styleClass="vote-failed" type="submit" actionListener="#{PollBean.vote(poll.idPollOptions)}" value="Votar"/>                          
                                    </ui:fragment>

                                    <ui:fragment rendered="#{((poll.idPoll.userVote.idPollOption.idPollOptions) ne (poll.idPollOptions) and (poll.idPoll.userVote.idPollOption) ne null)}">
                                        <h:commandButton styleClass="vote-failed" type="submit" actionListener="#{PollBean.change(poll.pollStat.idPollStats, poll.idPollOptions)}" value="Votar"/>  
                                    </ui:fragment>

                                    <h:outputLabel  value="#{poll.description}"/>
                                </li>
                            </ui:fragment>

                            <ui:fragment rendered="#{(login.isLogin) eq false}">
                                <li>                                    
                                    <h:outputLabel  value="#{poll.description}"/>
                                </li>
                            </ui:fragment>
                        </ui:repeat>
                    </ul>

                    <ui:fragment rendered="#{(login.isLogin) eq false}">
                        <h:outputLabel value="Inicia Sesión para votar"/>
                    </ui:fragment>
                    <input type="button" name="results" value="   Ver Resultados   " class="btn-vote"/>

                    <div class="votes">

                        <ul class="vote-p">
                            <ui:repeat value="#{PollBean.poll.percentage}" var="stat" varStatus="status" >
                                <li>

                                    <h:outputLabel styleClass="btn-vote" value="#{stat.percentage} % "/>

                                    <h:outputLabel styleClass="vote-label" value="#{stat.description}"/>
                                </li>
                            </ui:repeat>
                        </ul>

                    </div>
                </div>
            </div>
        </div><!-- widget -->
    </h:form>
</ui:composition>

WebSite/src/main/webapp/View/Index/Sermon.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <div class="posts_block mbf clearfix">
        <div class="title color6">
            <h4>Dios quiere hablarte hoy</h4>
        </div>
        <div class="carousel_TV">
            <ui:repeat value="#{VideoBean.videosIndex}" var="video" varStatus="status">
                <ui:fragment rendered="#{((status.index)+1) gt 0}">
                    <div class="item hover-shadow">
                        <h:link outcome="sermonDetail" >
                            <f:param name="id" value="#{video.idVideo}" />
                            <h:graphicImage url="#{video.image}" />
                        </h:link>
                        #{video.title}
                    </div>
                </ui:fragment>
            </ui:repeat>
        </div>
    </div>
</ui:composition>