WebSite/src/main/java/com/jjmsoftsolutions/bean/LoginBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.entity.Blog;
import com.jjmsoftsolutions.entity.BlogSession;
import com.jjmsoftsolutions.model.BlogModel;
import com.jjmsoftsolutions.model.LoginModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import static com.jjmsoftsolutions.utils.Session.getSession;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import static javax.faces.context.FacesContext.getCurrentInstance;
import javax.servlet.http.HttpSession;

@ManagedBean(name = "login")
@SessionScoped
public class LoginBean {
    
    private String name;
    private String password;
    private static HashMap<String, String> blogConnected;

    public LoginBean() {
        if (blogConnected == null) {
            blogConnected = new HashMap<String, String>();
        }
    }
    
     /**
     * @return the blogConnected
     */
    public static HashMap<String, String>  getBlogConnected() {
        return blogConnected;
    }

    /**
     * @param aBlogConnected the blogConnected to set
     */
    public static void setBlogConnected(HashMap<String, String> aBlogConnected) {
        blogConnected = aBlogConnected;
    }


    public void login() {
        Blog user = LoginModel.login(name, StringUtils.md5(password));
        if (user != null) {
            try {
                String ip = Session.getIp();

                BlogSession blogSession = new BlogSession();
                blogSession.setEmail(user);
                blogSession.setIp(ip);
                blogSession.setLoginDate(new Date());

                HttpSession session = getSession();
                session.setAttribute("user", user);
                user.setLastLoginDate(new Date());
                user.setLastIpAccess(ip);
                LoginModel.update(user);
                BlogModel.insertSession(blogSession);
                blogConnected.put(user.getEmail(), user.getEmail());
                Utility.redirect("Inicio");
                getBlogConnected().put(user.getEmail(), user.getEmail());
            } catch (Exception ex) {
                Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            user = LoginModel.isDisable(name, StringUtils.md5(password));
            if (user != null) {
                Utility.redirect("Cuenta-Deshabilitada");
            } else {
                Utility.redirect("Cuenta-Invalida");
            }
        }
    }

    public boolean getIsLogin() {
        return getUser() != null;
    }

    public Blog getUser() {
        HttpSession session = (HttpSession) getCurrentInstance().getExternalContext().getSession(false);
        Blog user = (Blog) session.getAttribute("user");
        return user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void logout() {
        blogConnected.remove(Session.getUser().getEmail());
        Session.logout();
        Utility.redirect("Inicio");
        
    }

    public void profile() {
        Utility.redirect("Perfil?id=".concat(Session.getUser().getEmail()).concat("&sermon=3&post=3"));
    }
    
    public boolean getUserIsConnected(){
        String email = JSFUtil.getParameterURL("id");
        if(blogConnected != null){
            return blogConnected.containsKey(email);
        }
        return false;
        
    }

}

WebSite/src/main/java/com/jjmsoftsolutions/bean/PictureAlbumBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.entity.Picture;
import com.jjmsoftsolutions.entity.PictureAlbum;
import com.jjmsoftsolutions.model.PictureAlbumModel;
import com.jjmsoftsolutions.model.PictureModel;
import com.jjmsoftsolutions.model.PropertiesModel;
import com.jjmsoftsolutions.utils.Constants;
import com.jjmsoftsolutions.utils.FtpUtil;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.Stateless;
import javax.faces.bean.ManagedBean;
import javax.servlet.http.Part;

@ManagedBean(name = "PictureAlbumBean")
@Stateless
public class PictureAlbumBean implements Serializable {

    private List<PictureAlbum> recentAlbums = null;
    private String sucessMessage;
    private String errorMessage;
    private Part file;

    public List<Picture> getPictureByAlbum() {
        return null;
    }

    public List<PictureAlbum> getAlbums() {
        List<PictureAlbum> list = PictureAlbumModel.getAllAlbums();
        return list;
    }

    public PictureAlbum getAlbum() {
        int id = StringUtils.getInt(JSFUtil.getParameterURL("id"));
        return PictureAlbumModel.getAlbumById(id);
    }

    public List<Picture> getPicturesByIdAlbum() {
        int id = StringUtils.getInt(JSFUtil.getParameterURL("id"));
        PictureAlbum album = PictureAlbumModel.getAlbumById(id);
        if (album != null) {
            return album.getPictureList();
        }
        return null;
    }

    public List<Picture> getCoreografiaMinisterio() {
        String category = "min-coreografia";
        PictureAlbum album = PictureAlbumModel.getAlbum(category);
        if (album != null) {
            return album.getPictureList();
        }
        return null;
    }

    public List<Picture> getPictureSlinder() {
        int pagination = PropertiesModel.getSlinderPagination();
        return PictureModel.getPicturesByAlbum("Slinder", pagination);
    }

    public List<Picture> getAllPictureSlinder() {
        return PictureModel.getPicturesByAlbum("Slinder");
    }

    public List<PictureAlbum> getRecentAlbums() {
        int max = 9;
        recentAlbums = PictureAlbumModel.getRecentAlbums(max);
        return recentAlbums;
    }

    /**
     * @param recentAlbums the recentAlbums to set
     */
    public void setRecentAlbums(List<PictureAlbum> recentAlbums) {
        this.recentAlbums = recentAlbums;
    }

    /**
     * @return the sucessMessage
     */
    public String getSucessMessage() {
        return sucessMessage;
    }

    /**
     * @param sucessMessage the sucessMessage to set
     */
    public void setSucessMessage(String sucessMessage) {
        this.sucessMessage = sucessMessage;
    }

    /**
     * @return the errorMessage
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * @param errorMessage the errorMessage to set
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public void insertSlinder() {
        if (file != null) {
            try {
                String fileName = Utility.getFileName(file);
                Picture picture = new Picture();
                picture.setPictureDate(new Date());
                picture.setIdPictureAlbum(PictureAlbumModel.getAlbum("Slinder"));
                picture.setTitle("");
                FtpUtil.upload("img/slinder", file.getInputStream(), fileName);
                picture.setUrl(Constants.SLINDER_PICTURE.concat(fileName));
                PictureModel.insert(picture);
                sucessMessage = "Ingresada correctamente";
                errorMessage = "";
            } catch (IOException ex) {
                Logger.getLogger(PictureAlbumBean.class.getName()).log(Level.SEVERE, null, ex);
                errorMessage = "Error al ingresar la imágen";
                sucessMessage = "";
            }

        }

    }

    /**
     * @return the file
     */
    public Part getFile() {
        return file;
    }

    /**
     * @param file the file to set
     */
    public void setFile(Part file) {
        this.file = file;
    }

    public void delete(Picture picture) {
        int idx = picture.getUrl().lastIndexOf("/") + 1;
        String fileName = picture.getUrl().substring(idx);
        FtpUtil.delete("img/slinder", fileName);
        PictureModel.delete(picture.getIdPicture());
    }

}

WebSite/src/main/java/com/jjmsoftsolutions/bean/PostBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.domain.Tag;
import com.jjmsoftsolutions.entity.Post;
import com.jjmsoftsolutions.entity.PostComment;
import com.jjmsoftsolutions.model.PostModel;
import com.jjmsoftsolutions.model.VideoModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "PostBean")
@ViewScoped
public class PostBean implements Serializable {

    private Post post;
    private List<Post> popular;
    private List<Post> news;

    private PostComment comment = new PostComment();

    public Post getLastPost() {
        setPost(PostModel.getLastPost("Reflexion"));
        return getPost();
    }

    public List<Post> getEvents() {
        String category = "Eventos";
        int end = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        return PostModel.getAllPostByCategory(category, end);
    }

    public Post getPostById() {
        setPost(PostModel.getPostById(StringUtils.getInt(JSFUtil.getParameterURL("id"))));
        return getPost();
    }

    public Post getEventById() {
        setPost(PostModel.getPostByIdCategory(StringUtils.getInt(JSFUtil.getParameterURL("id")), "Eventos"));
        return getPost();
    }

    public List<Post> getPopularPost() {
        setPopular(PostModel.getPopularPost(8));
        return getPopular();
    }

    public List<Post> getCuriosities() {
        return PostModel.getPostByCategory("Curiosidades", 10);
    }

    public List<Post> getNewsIndex() {
        setNews(PostModel.getPostByCategory("Eventos", 9));
        return getNews();
    }

    /**
     * @return the post
     */
    public Post getPost() {
        return post;
    }

    /**
     * @param post the post to set
     */
    public void setPost(Post post) {
        this.post = post;
    }

    /**
     * @return the popular
     */
    public List<Post> getPopular() {
        return popular;
    }

    /**
     * @param popular the popular to set
     */
    public void setPopular(List<Post> popular) {
        this.popular = popular;
    }

    /**
     * @return the news
     */
    public List<Post> getNews() {
        return news;
    }

    /**
     * @param news the news to set
     */
    public void setNews(List<Post> news) {
        this.news = news;
    }

    public void postComment() {
        getComment().setCommentDate(new Date());
        getComment().setEmail(Session.getUser());
        getComment().setIdPost(post);
        PostModel.postComment(getComment());
        Utility.redirect("Post?id=" + post.getIdPost());
    }

    /**
     * @return the comment
     */
    public PostComment getComment() {
        return comment;
    }

    /**
     * @param comment the comment to set
     */
    public void setComment(PostComment comment) {
        this.comment = comment;
    }

    public void deletePostComment(int id) {
        PostModel.delete(id);
        Utility.redirect("post.xhtml?id=" + post.getIdPost());
    }

    public List<Tag> getTotalButtons() {

        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        int totalRecord = PostModel.getCountByCategory("Eventos");
        return Utility.getTag(3, totalRecord, pagination);
    }

    public List<PostComment> getCommentsByBlog() {
        String email = JSFUtil.getParameterURL("id");
        int totalRecords = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        return PostModel.getAllPostByCommentsByBlog(email, totalRecords);
    }

    public List<Tag> getTotalCommentsPost() {
        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        int totalRecord = PostModel.getCountCommentsByBlog(JSFUtil.getParameterURL("id"));
        return Utility.getTag(3, totalRecord, pagination);

    }

}

WebSite/src/main/java/com/jjmsoftsolutions/bean/VideoBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.domain.Tag;
import com.jjmsoftsolutions.entity.Video;
import com.jjmsoftsolutions.entity.VideoComments;
import com.jjmsoftsolutions.model.VideoModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "VideoBean")
@ViewScoped
public class VideoBean implements Serializable {

    private Video video;
    private int totalVideos;
    private List<Video> music;
    private List<Video> popularSermonList;

    private VideoComments comment = new VideoComments();

    public Video getLastVideo() {
        setVideo(VideoModel.getLastVideo());
        return getVideo();
    }

    public void postComment() {
        comment.setCommentDate(new Date());
        comment.setEmail(Session.getUser());
        comment.setIdVideo(video);
        VideoModel.postComment(comment);
        Utility.redirect("Predicas?id=" + video.getIdVideo());
    }

    public void deletePostComment(int id) {
        VideoModel.delete(id);
        Utility.redirect("Predicas?id=" + video.getIdVideo());
    }

    public List<Video> getVideosIndex() {
        List<Video> list = VideoModel.getVideos("Predicas", 8);
        return list;
    }

    public List<Video> getPopularSermon() {
        popularSermonList = VideoModel.getPopularSermon("Predicas", 8);
        return popularSermonList;
    }

    public List<Video> getMusicIndex() {
        setMusic(VideoModel.getVideos("Musica", 9));
        return getMusic();
    }

    public Video getVideoById() {
        setVideo(VideoModel.getVideoById(StringUtils.getInt(JSFUtil.getParameterURL("id"))));
        return getVideo();
    }

    public List<Video> getAllVideosMusic() {
        List<Video> list = VideoModel.getAllVideosByAlbum("Musica");
        return list;
    }

    public List<Video> getAllVideosSermon() {
        String category = "Predicas";
        int end = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        List<Video> list = VideoModel.getVideosByCategoryPagination(category, end);
        return list;
    }

    public List<Tag> getTotalButtons() {
        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        int totalRecord = VideoModel.getCountByCategory("Predicas");
        return Utility.getTag(3, totalRecord, pagination);
    }

    public List<Tag> getTotalCommentsVideos() {
        int totalRecord = VideoModel.getCountCommentsByBlog(JSFUtil.getParameterURL("id"));
        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("sermon"));        
        return Utility.getTag(3, totalRecord, pagination);
    }

    public List<VideoComments> getCommentsByBlog() {
        String email = JSFUtil.getParameterURL("id");
        int totalRecords = StringUtils.getInt(JSFUtil.getParameterURL("sermon"));
        List<VideoComments> list = VideoModel.getCommentsByBlog(email, totalRecords);
        return list;
    }

    /**
     * @return the video
     */
    public Video getVideo() {
        return video;
    }

    /**
     * @param video the video to set
     */
    public void setVideo(Video video) {
        this.video = video;
    }

    /**
     * @return the music
     */
    public List<Video> getMusic() {
        return music;
    }

    /**
     * @param music the music to set
     */
    public void setMusic(List<Video> music) {
        this.music = music;
    }

    /**
     * @return the popularSermonList
     */
    public List<Video> getPopularSermonList() {
        return popularSermonList;
    }

    /**
     * @param popularSermonList the popularSermonList to set
     */
    public void setPopularSermonList(List<Video> popularSermonList) {
        this.popularSermonList = popularSermonList;
    }

    /**
     * @return the comment
     */
    public VideoComments getComment() {
        return comment;
    }

    /**
     * @param comment the comment to set
     */
    public void setComment(VideoComments comment) {
        this.comment = comment;
    }

}

WebSite/src/main/webapp/celula.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <ui:include src="/css.xhtml" /> 
    </h:head>
    <h:body>
        <div id="layout" class="boxed-margin">

            <ui:include src="/section/menu.xhtml" /> 

            <div class="page-content">			
                <div class="row clearfix">

                    <ui:include src="/webSiteConstruction.xhtml" /> 

                    <!--
                    <div class="logo">

                    </div>
                    <div class="ads">
                        <div class = "img-text">
                            <img src="http://162.253.126.108/~ucbdpdbn/public/img/logo/+Q.png" width="50px"/>

                        </div>
                        <div class = "img-text">
                            Iglesia CCI Vida Abundante - <span>Red Juvenil</span>
                        </div>
                    </div>

                    <div class="grid_12 alpha">

                        <div class="grid_9 alpha posts">
                            <div class="title color6">
                                <h4>Prédicas</h4>
                            </div>
                            <ui:repeat value="#{VideoBean.allVideosSermon}" var="video" varStatus="status">

                                <div class="post_day mbf clearfix">
                                    <div class="grid_6 alpha relative">
                                        <a class="hover-shadow" href="sermonDetail.xhtml?id=#{video.idVideo}">
                                            <img src="#{video.image}" alt=""/>
                                        </a>
                                    </div>
                                    <div class="grid_6 omega">
                                        <div class="post_day_content">
                                            <h3> 
                                                <a href="sermonDetail.xhtml?id=#{video.idVideo}">#{video.title}</a> 
                                            </h3>
                                            <div class="meta mb"> 
                                                <strong>Fecha:</strong> #{video.videoDate}   /    <a href="single_post.html">#{video.videoCommentsList.size()} comentarios</a> 
                                            </div>
                                            <p> 
                    #{video.description}
                </p>
            </div>
        </div>
    </div>
</ui:repeat>
<div class="pagination-tt clearfix">
    <ul>
        <li><span>1</span></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">27</a></li>
    </ul>

</div>

</div>
<div class="grid_3 omega sidebar sidebar_a">



<ui:include src="/section/popularSermon.xhtml" /> 



<ui:include src="/section/facebookSocial.xhtml" />

</div>

</div>
                    -->
                </div><!-- /end page content -->
            </div><!-- /end page content -->
            <ui:include src="/section/footer.xhtml" /> 

        </div><!-- /layout -->

        <!-- Scripts -->
        <ui:include src="/js.xhtml" /> 

    </h:body>
</html>

WebSite/src/main/webapp/coreografia.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <ui:include src="/css.xhtml" /> 
    </h:head>
    <h:body>
        <div id="layout" class="boxed-margin">

            <ui:include src="/section/menu.xhtml" /> 

            <div class="page-content">			
                <div class="row clearfix">
                    <div class="logo">

                    </div><!-- /logo -->
                    <div class="ads">
                        <div class = "img-text">
                            <img src="http://162.253.126.108/~ucbdpdbn/public/img/logo/+Q.png"  width="50px"/>

                        </div>
                        <div class = "img-text">
                            Iglesia CCI Vida Abundante - <span>Red Juvenil</span>
                        </div>

                    </div><!-- /ads -->

                    <div class="grid_12 alpha">

                        <div class="grid_12 alpha posts">
                            <div class="title color5">
                                <h4>Coreografía</h4>
                            </div>


                            <!-- END PAGE META -->
                            <!-- START PRIMARY -->
                            <div id="primary" class="sidebar-no">
                                <div class="inner group">
                                    <!-- START CONTENT -->
                                    <div id="content-page" class="content group">
                                        <div class="hentry group">                                        
                                            <ul id="portfolio" class="three-columns">

                                                <c:forEach items="#{PictureAlbumBean.coreografiaMinisterio}" var="album" varStatus="status">
                                                    <c:choose>
                                                        <c:when  test="#{(status.index+1)%2 eq 1}">
                                                            <li class="first slide-1 first one-third">
                                                                <a class="" href="#" rel="lightbox" >
                                                                    <img src="#{album.url}" style="width:265px; height:265px"/>
                                                                </a>
                                                                <h4>
                                                                    <a href="#">#{album.title}</a>
                                                                </h4>
                                                            </li>
                                                        </c:when>
                                                        <c:otherwise>
                                                            <li class="slide-2  one-third">
                                                                <a class="" href="#" rel="lightbox" ><!--thumb video -->
                                                                    <img src="#{album.url}" style="width:265px; height:265px"/>
                                                                </a>
                                                                <h4>
                                                                    <a href="#">#{album.title}</a>
                                                                </h4>
                                                            </li>
                                                        </c:otherwise>
                                                    </c:choose>
                                                </c:forEach>
                                            </ul>
                                        </div>
                                        <!-- START COMMENTS -->
                                        <div id="comments">
                                        </div>
                                        <!-- END COMMENTS -->
                                    </div>
                                    <!-- END CONTENT -->
                                    <!-- START EXTRA CONTENT -->
                                    <!-- END EXTRA CONTENT -->
                                </div>
                            </div>
                            <!-- END PRIMARY -->



                        </div><!-- end grid9 -->



                    </div><!-- /row -->
                </div><!-- /end page content -->
            </div><!-- /end page content -->
            <ui:include src="/section/footer.xhtml" /> 

        </div><!-- /layout -->

        <ui:include src="/js.xhtml" /> 
    </h:body>
</html>

WebSite/src/main/webapp/sermon.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <ui:include src="/css.xhtml" /> 
    </h:head>
    <h:body>
        <div id="layout" class="boxed-margin">

            <ui:include src="/section/menu.xhtml" /> 

            <div class="page-content">			
                <div class="row clearfix">
                    <ui:include src="/section/logo.xhtml" /> 

                    <div class="grid_12 alpha">

                        <div class="grid_9 alpha posts">
                            <div class="title color6">
                                <h4>Prédicas</h4>
                            </div>
                            <ui:repeat value="#{VideoBean.allVideosSermon}" var="video" varStatus="status">
                                <!-- post -->
                                <div class="post_day mbfd clearfix">

                                    <div class="grid_6 alpha relative">
                                        <!--<div class="grid_6_date">
                                            <span class="month">DEC</span>
                                            <span class="day">12</span>
                                        </div>
                                        -->
                                        <a  href="Predicas?id=#{video.idVideo}">
                                            <img src="#{video.image}" alt="" />
                                        </a>
                                    </div><!-- /grid6 alpha -->
                                    <div class="grid_6 omega">
                                        <div class="post_day_content">
                                            <div class="post_dat_content_title">

                                                <div class="title-meta">
                                                    <a href="Predicas?id=#{video.idVideo}">#{video.title}</a> 
                                                </div>

                                                <div class="meta mb"> 
                                                    <ul>


                                                        <li class="calendar-meta">
                                                            <p>
                                                                Fecha: #{video.videoDate}
                                                            </p>                                                            
                                                        </li>
                                                        <li class="comment-meta">
                                                            <p>
                                                                #{video.videoCommentsList.size()} comentario(s)
                                                            </p>
                                                        </li>
                                                    </ul>
                                                </div>


                                            </div>
                                            <div class="content_meta">
                                                <p> 
                                                    #{video.description}
                                                </p>
                                            </div>

                                            
                                        </div><!-- /grid6 omega -->
                                    </div><!-- /post day -->
                                </div>
                                <!-- /post -->
                            </ui:repeat>
                            <div class="pagination-tt clearfix">
                                <ul>
                                    <ui:repeat value="#{VideoBean.totalButtons}" var="tag" varStatus="status">
                                        <ui:fragment rendered="#{tag.selected eq true}">
                                            <li>
                                                <span>#{status.index+1}</span>
                                            </li>
                                        </ui:fragment>

                                        <ui:fragment rendered="#{tag.selected eq false}">
                                            <li>
                                                <h:link outcome="sermon" value="#{status.index+1}">                                    
                                                    <f:param name="end" value="#{tag.number}" />
                                                </h:link>         

                                            </li>
                                        </ui:fragment>

                                    </ui:repeat>


                                </ul>

                            </div><!-- /pagination -->

                        </div><!-- end grid9 -->
                        <div class="grid_3 omega sidebar sidebar_a">



                            <ui:include src="/section/popularSermon.xhtml" /> 




                            <!-- <ui:include src="/section/recentComments.xhtml" /> -->


                        </div><!-- /grid3 sidebar A -->

                    </div><!-- /row -->
                </div><!-- /end page content -->
            </div><!-- /end page content -->
            <ui:include src="/section/footer.xhtml" /> 

        </div><!-- /layout -->

        <!-- Scripts -->
        <ui:include src="/js.xhtml" /> 

    </h:body>
</html>