WebSite/src/main/java/com/jjmsoftsolutions/bean/LoginBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.entity.Blog;
import com.jjmsoftsolutions.entity.BlogSession;
import com.jjmsoftsolutions.model.BlogModel;
import com.jjmsoftsolutions.model.LoginModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import static com.jjmsoftsolutions.utils.Session.getSession;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import static javax.faces.context.FacesContext.getCurrentInstance;
import javax.servlet.http.HttpSession;

@ManagedBean(name = "login")
@SessionScoped
public class LoginBean {
    
    private String name;
    private String password;
    private static HashMap<String, String> blogConnected;

    public LoginBean() {
        if (blogConnected == null) {
            blogConnected = new HashMap<String, String>();
        }
    }
    
     /**
     * @return the blogConnected
     */
    public static HashMap<String, String>  getBlogConnected() {
        return blogConnected;
    }

    /**
     * @param aBlogConnected the blogConnected to set
     */
    public static void setBlogConnected(HashMap<String, String> aBlogConnected) {
        blogConnected = aBlogConnected;
    }


    public void login() {
        Blog user = LoginModel.login(name, StringUtils.md5(password));
        if (user != null) {
            try {
                String ip = Session.getIp();

                BlogSession blogSession = new BlogSession();
                blogSession.setEmail(user);
                blogSession.setIp(ip);
                blogSession.setLoginDate(new Date());

                HttpSession session = getSession();
                session.setAttribute("user", user);
                user.setLastLoginDate(new Date());
                user.setLastIpAccess(ip);
                LoginModel.update(user);
                BlogModel.insertSession(blogSession);
                blogConnected.put(user.getEmail(), user.getEmail());
                Utility.redirect("Inicio");
                getBlogConnected().put(user.getEmail(), user.getEmail());
            } catch (Exception ex) {
                Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            user = LoginModel.isDisable(name, StringUtils.md5(password));
            if (user != null) {
                Utility.redirect("Cuenta-Deshabilitada");
            } else {
                Utility.redirect("Cuenta-Invalida");
            }
        }
    }

    public boolean getIsLogin() {
        return getUser() != null;
    }

    public Blog getUser() {
        HttpSession session = (HttpSession) getCurrentInstance().getExternalContext().getSession(false);
        Blog user = (Blog) session.getAttribute("user");
        return user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void logout() {
        blogConnected.remove(Session.getUser().getEmail());
        Session.logout();
        Utility.redirect("Inicio");
        
    }

    public void profile() {
        Utility.redirect("Perfil?id=".concat(Session.getUser().getEmail()).concat("&sermon=3&post=3"));
    }
    
    public boolean getUserIsConnected(){
        String email = JSFUtil.getParameterURL("id");
        if(blogConnected != null){
            return blogConnected.containsKey(email);
        }
        return false;
        
    }

}

WebSite/src/main/java/com/jjmsoftsolutions/bean/PostBean.java
package com.jjmsoftsolutions.bean;

import com.jjmsoftsolutions.domain.Tag;
import com.jjmsoftsolutions.entity.Post;
import com.jjmsoftsolutions.entity.PostComment;
import com.jjmsoftsolutions.model.PostModel;
import com.jjmsoftsolutions.model.VideoModel;
import com.jjmsoftsolutions.utils.JSFUtil;
import com.jjmsoftsolutions.utils.Session;
import com.jjmsoftsolutions.utils.StringUtils;
import com.jjmsoftsolutions.utils.Utility;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "PostBean")
@ViewScoped
public class PostBean implements Serializable {

    private Post post;
    private List<Post> popular;
    private List<Post> news;

    private PostComment comment = new PostComment();

    public Post getLastPost() {
        setPost(PostModel.getLastPost("Reflexion"));
        return getPost();
    }

    public List<Post> getEvents() {
        String category = "Eventos";
        int end = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        return PostModel.getAllPostByCategory(category, end);
    }

    public Post getPostById() {
        setPost(PostModel.getPostById(StringUtils.getInt(JSFUtil.getParameterURL("id"))));
        return getPost();
    }

    public Post getEventById() {
        setPost(PostModel.getPostByIdCategory(StringUtils.getInt(JSFUtil.getParameterURL("id")), "Eventos"));
        return getPost();
    }

    public List<Post> getPopularPost() {
        setPopular(PostModel.getPopularPost(8));
        return getPopular();
    }

    public List<Post> getCuriosities() {
        return PostModel.getPostByCategory("Curiosidades", 10);
    }

    public List<Post> getNewsIndex() {
        setNews(PostModel.getPostByCategory("Eventos", 9));
        return getNews();
    }

    /**
     * @return the post
     */
    public Post getPost() {
        return post;
    }

    /**
     * @param post the post to set
     */
    public void setPost(Post post) {
        this.post = post;
    }

    /**
     * @return the popular
     */
    public List<Post> getPopular() {
        return popular;
    }

    /**
     * @param popular the popular to set
     */
    public void setPopular(List<Post> popular) {
        this.popular = popular;
    }

    /**
     * @return the news
     */
    public List<Post> getNews() {
        return news;
    }

    /**
     * @param news the news to set
     */
    public void setNews(List<Post> news) {
        this.news = news;
    }

    public void postComment() {
        getComment().setCommentDate(new Date());
        getComment().setEmail(Session.getUser());
        getComment().setIdPost(post);
        PostModel.postComment(getComment());
        Utility.redirect("Post?id=" + post.getIdPost());
    }

    /**
     * @return the comment
     */
    public PostComment getComment() {
        return comment;
    }

    /**
     * @param comment the comment to set
     */
    public void setComment(PostComment comment) {
        this.comment = comment;
    }

    public void deletePostComment(int id) {
        PostModel.delete(id);
        Utility.redirect("post.xhtml?id=" + post.getIdPost());
    }

    public List<Tag> getTotalButtons() {

        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("end"));
        int totalRecord = PostModel.getCountByCategory("Eventos");
        return Utility.getTag(3, totalRecord, pagination);
    }

    public List<PostComment> getCommentsByBlog() {
        String email = JSFUtil.getParameterURL("id");
        int totalRecords = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        return PostModel.getAllPostByCommentsByBlog(email, totalRecords);
    }

    public List<Tag> getTotalCommentsPost() {
        int pagination = StringUtils.getInt(JSFUtil.getParameterURL("post"));
        int totalRecord = PostModel.getCountCommentsByBlog(JSFUtil.getParameterURL("id"));
        return Utility.getTag(3, totalRecord, pagination);

    }

}

WebSite/src/main/java/com/jjmsoftsolutions/entity/Video.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jjmsoftsolutions.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author luis
 */
@Entity
@Table(name = "VIDEO")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Video.findAll", query = "SELECT v FROM Video v"),
    @NamedQuery(name = "Video.findByIdVideo", query = "SELECT v FROM Video v WHERE v.idVideo = :idVideo"),
    @NamedQuery(name = "Video.findByVideoDate", query = "SELECT v FROM Video v WHERE v.videoDate = :videoDate")})
public class Video implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID_VIDEO")
    private Integer idVideo;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 2147483647)
    @Column(name = "URL")
    private String url;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 2147483647)
    @Column(name = "TITLE")
    private String title;
    @Lob
    @Size(max = 2147483647)
    @Column(name = "DESCRIPTION")
    private String description;
    @Basic(optional = false)
    @NotNull
    @Column(name = "VIDEO_DATE")
    @Temporal(TemporalType.DATE)
    private Date videoDate;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idVideo", fetch = FetchType.LAZY)
    private List<VideoComments> videoCommentsList;
    @JoinColumn(name = "ID_EXPONENT", referencedColumnName = "ID_EXPONENT")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Exponent idExponent;
    @JoinColumn(name = "ID_VIDEO_ALBUM", referencedColumnName = "ID_VIDEO_ALBUM")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private VideoAlbum idVideoAlbum;

    public Video() {
    }

    public Video(Integer idVideo) {
        this.idVideo = idVideo;
    }

    public Video(Integer idVideo, String url, String title, Date videoDate) {
        this.idVideo = idVideo;
        this.url = url;
        this.title = title;
        this.videoDate = videoDate;
    }

    public Integer getIdVideo() {
        return idVideo;
    }

    public void setIdVideo(Integer idVideo) {
        this.idVideo = idVideo;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getVideoDate() {
        return videoDate;
    }

    public void setVideoDate(Date videoDate) {
        this.videoDate = videoDate;
    }

    @XmlTransient
    public List<VideoComments> getVideoCommentsList() {
        return videoCommentsList;
    }

    public void setVideoCommentsList(List<VideoComments> videoCommentsList) {
        this.videoCommentsList = videoCommentsList;
    }

    public Exponent getIdExponent() {
        return idExponent;
    }

    public void setIdExponent(Exponent idExponent) {
        this.idExponent = idExponent;
    }

    public VideoAlbum getIdVideoAlbum() {
        return idVideoAlbum;
    }

    public void setIdVideoAlbum(VideoAlbum idVideoAlbum) {
        this.idVideoAlbum = idVideoAlbum;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idVideo != null ? idVideo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Video)) {
            return false;
        }
        Video other = (Video) object;
        if ((this.idVideo == null && other.idVideo != null) || (this.idVideo != null && !this.idVideo.equals(other.idVideo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.jjmsoftsolutions.entity.Video[ idVideo=" + idVideo + " ]";
    }

    public String getImage() {
        return "http://img.youtube.com/vi/" + getCode() + "/0.jpg";
    }

    public String getURLYoutube() {
        return "http://www.youtube.com/embed/" + getCode() + "?wmode=transparent";
    }

    public String getCode() {
        String img;
        if (this.url.contains("https")) {
            img = this.url.substring(32);
        } else {
            img = this.url.substring(31);
        }
        return img;
    }

}

WebSite/src/main/webapp/section/profile/activity.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <div class="profile_content userprof" id="t-1">

        <div id="moreactivity_container" class="moreactivity">
            <span id="noresults" class="hiden">Mis comentarios acerca de las prédicas</span>
        </div>

        <ui:repeat value="#{VideoBean.commentsByBlog}" var="video" varStatus="status">

            <li class="activitybit forum_post active " >
                <div class="avatar">
                    <img src="#{video.idVideo.image}" width="60px" height="60px" alt="Administrator's Avatar" />
                </div>

                <div class="content hasavatar">

                    <div class="datetime">
                        <span class="date">#{video.commentDate}</span>
                    </div>

                    <div class="title">
                        <span>
                            #{video.idVideo.title}
                        </span>

                    </div>

                    <div class="excerpt">
                        #{video.comment}

                    </div>

                    <div class="fulllink">
                        <h:link outcome="sermonDetail" value="Ver publicación">
                            <f:param name="id" value="#{video.idVideo.idVideo}" />
                        </h:link>
                    </div>

                    <div class="views">#{video.idVideo.videoCommentsList.size()} comentario(s)</div>

                </div>

            </li>



        </ui:repeat>

        <div id="pagination_bottom">

            <div class="pagination popupmenu nohovermenu">
                <ui:repeat value="#{VideoBean.totalCommentsVideos}" var="tag" varStatus="status">
                    <ui:fragment rendered="#{tag.selected eq true}">
                        <span class="selected">
                            <!--
                                                        <h:link outcome="profile" value="#{status.index+1}">
                                                            <f:param name="id" value="#{BlogBean.blog.email}" />
                                                            <f:param name="sermon" value="#{tag.number}" />
                                                            <f:param name="post" value="#{GeneralBean.postParameter}" />
                                                        </h:link>
                            -->
                            <c:choose>
                                <c:when  test="#{login.isLogin}">              

                                    <ui:fragment rendered="#{GeneralBean.emailParameter eq login.user.email}">
                                        <h:link outcome="profile" value="#{status.index+1}">
                                            <f:param name="id" value="#{BlogBean.blog.email}" />
                                            <f:param name="sermon" value="#{tag.number}" />
                                            <f:param name="post" value="#{GeneralBean.postParameter}" />
                                        </h:link>
                                    </ui:fragment>

                                    <ui:fragment rendered="#{GeneralBean.emailParameter ne login.user.email}">
                                        <h:link outcome="profile2" value="#{status.index+1}">
                                            <f:param name="id" value="#{BlogBean.blog.email}" />
                                            <f:param name="sermon" value="#{tag.number}" />
                                            <f:param name="post" value="#{GeneralBean.postParameter}" />
                                        </h:link>
                                    </ui:fragment>
                                </c:when>
                                <c:otherwise>          
                                    <h:link outcome="profile2" value="#{status.index+1}">
                                        <f:param name="id" value="#{BlogBean.blog.email}" />
                                        <f:param name="sermon" value="#{tag.number}" />
                                        <f:param name="post" value="#{GeneralBean.postParameter}" />
                                    </h:link>
                                </c:otherwise>
                            </c:choose>
                        </span>
                    </ui:fragment>

                    <ui:fragment rendered="#{tag.selected eq false}">
                        <span>
                            <c:choose>
                                <c:when  test="#{login.isLogin}">              

                                    <ui:fragment rendered="#{GeneralBean.emailParameter eq login.user.email}">
                                        <h:link outcome="profile" value="#{status.index+1}">
                                            <f:param name="id" value="#{BlogBean.blog.email}" />
                                            <f:param name="sermon" value="#{tag.number}" />
                                            <f:param name="post" value="#{GeneralBean.postParameter}" />
                                        </h:link>
                                    </ui:fragment>

                                    <ui:fragment rendered="#{GeneralBean.emailParameter ne login.user.email}">
                                        <h:link outcome="profile2" value="#{status.index+1}">
                                            <f:param name="id" value="#{BlogBean.blog.email}" />
                                            <f:param name="sermon" value="#{tag.number}" />
                                            <f:param name="post" value="#{GeneralBean.postParameter}" />
                                        </h:link>
                                    </ui:fragment>
                                </c:when>
                                <c:otherwise>          
                                    <h:link outcome="profile2" value="#{status.index+1}">
                                        <f:param name="id" value="#{BlogBean.blog.email}" />
                                        <f:param name="sermon" value="#{tag.number}" />
                                        <f:param name="post" value="#{GeneralBean.postParameter}" />
                                    </h:link>
                                </c:otherwise>
                            </c:choose>
                        </span>
                    </ui:fragment>

                </ui:repeat>
            </div>
            <div class="clear"></div>

        </div>




        <ui:repeat value="#{PostBean.commentsByBlog}" var="comment" varStatus="status">

            <ui:fragment rendered="#{status.index == 0}">
                <div id="moreactivity_container" class="moreactivity">
                    <span id="noresults" class="hiden">Mis comentarios acerca de los post</span>
                </div>
            </ui:fragment>
            <li class="activitybit forum_post active " >
                <div class="avatar">
                    <img src="#{comment.idPost.picture}" width="60px" height="60px" alt="Administrator's Avatar" />
                </div>

                <div class="content hasavatar">

                    <div class="datetime">
                        <span class="date">#{comment.commentDate}</span>
                    </div>

                    <div class="title">
                        <span>
                            #{comment.idPost.title}
                        </span>

                    </div>

                    <div class="excerpt">
                        #{comment.comment}
                    </div>

                    <div class="fulllink">
                        <h:link outcome="post" value="Ver publicación">
                            <f:param name="id" value="#{comment.idPost.idPost}" />

                        </h:link>
                    </div>

                    <div class="views">#{comment.idPost.postCommentList.size()} comentario(s)</div>

                </div>

            </li>



        </ui:repeat>

        <div id="pagination_bottom">

            <div class="pagination popupmenu nohovermenu">
                <ui:repeat value="#{PostBean.totalCommentsPost}" var="tag" varStatus="status">
                    <ui:fragment rendered="#{tag.selected eq true}">
                        <span class="selected">
                            <h:link outcome="profile" value="#{status.index+1}">
                                <f:param name="id" value="#{BlogBean.blog.email}" />
                                <f:param name="sermon" value="#{GeneralBean.sermonParameter}" />
                                <f:param name="post" value="#{tag.number}" />
                            </h:link>

                        </span>
                    </ui:fragment>

                    <ui:fragment rendered="#{tag.selected eq false}">
                        <span>
                            <h:link outcome="profile" value="#{status.index+1}">
                                <f:param name="id" value="#{BlogBean.blog.email}" />
                                <f:param name="sermon" value="#{GeneralBean.sermonParameter}" />
                                <f:param name="post" value="#{tag.number}" />
                            </h:link>
                        </span>
                    </ui:fragment>

                </ui:repeat>
            </div>
            
            
            <div class="clear"></div>

        </div>




    </div>


</ui:composition>

WebSite/src/main/webapp/section/profile/changePassword.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <h:form enctype="multipart/form-data" id="profileForm">

       

            <div id="moreactivity_container" class="moreactivity">
                <span id="noresults" class="hiden">Cambiar Contraseña</span>
            </div>

            <div id="moreactivity_container" class="security forum_post active">  
                <div class="header_profile">
                    Contraseña Antigua 
                </div>

                <h:inputSecret id="oldPassword" value="#{BlogBean.oldPassword}" required="true" requiredMessage="Requerido"/>
                <h:message for="oldPassword" id="msgOldPassword" styleClass="validator-message-error"/>


            </div>

            <div id="moreactivity_container" class="security forum_post active">  
                <div class="header_profile">
                    Nueva Contraseña: 
                </div>
                <h:inputSecret id="newPassword" value="#{BlogBean.newPassword}" required="true" requiredMessage="Requerido"/> 
                <h:message for="newPassword" id="msgNewPassword" styleClass="validator-message-error"/> 
            </div>

            <div id="moreactivity_container" class="security forum_post active">  
                <div class="header_profile">
                    Repita la Contraseña: 
                </div>
                <h:inputSecret id="revalidatePassword" value="#{BlogBean.revalidatePassword}" required="true" requiredMessage="Requerido"/>      
                <h:message for="revalidatePassword" id="msgRevalidatePassword" styleClass="validator-message-error"/> 
            </div>







             <div id="moreactivity_container" class="update-panel">
                <h:commandButton value="Cambiar" styleClass="cancel-account color-button1" type="submit" actionListener="#{BlogBean.changePassword}">
                    <f:ajax execute="@form" render="msgOldPassword msgNewPassword msgRevalidatePassword msgSlinderPanel" />    <!-- msgNewPassword msgRevalidatePassword-->     
                </h:commandButton>

                <p:ajaxStatus>
                    <f:facet name="start">
                        <div class="loading-profile password-panel">
                            <p>
                                <img src="resources/images/loading.gif" alt="" />                         
                                <h:outputLabel  value="Cargando..." />         
                            </p>
                        </div>
                    </f:facet>
                    <f:facet name="complete">
                        <p>
                            <h:panelGroup id="msgSlinderPanel">
                                <h:outputText value=" " />
                                <h:outputText id="msgSuccess" value="#{BlogBean.sucessMessage}" styleClass="succes-msg" rendered="#{BlogBean.sucessMessage ne null}" />
                                <h:outputText id="msgError" value="#{BlogBean.errorMessage}" styleClass="error-msg" rendered="#{BlogBean.errorMessage ne null}" />
                            </h:panelGroup>
                        </p>
                    </f:facet>
                </p:ajaxStatus>
            </div>

      
    </h:form>
</ui:composition>

WebSite/src/main/webapp/section/profile/changePhoto.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:form enctype="multipart/form-data" >
        <div id="moreactivity_container" class="moreactivity">
            <span id="noresults" class="hiden">Cambiar Fotografía</span>
        </div>
        <div id="moreactivity_container" class="security forum_post active">  
            <div class="header_profile">
                Fotografía: 
            </div>
            <h:inputFile value="#{BlogBean.file}" id="file" /> 
        </div>
        <div id="moreactivity_container" >
            <h:commandButton value="Cambiar" styleClass="cancel-account color-button1" type="submit" actionListener="#{BlogBean.changePhoto}"/>
        </div>
    </h:form>
</ui:composition>